version = 0.1
[default.deploy.parameters]
stack_name = "open-meteo-api-stack"
resolve_s3 = true
s3_prefix = "open-meteo-api-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"open-meteo-api-pressure-data\""
image_repositories = []
