AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Description: S3 bucket name for storing pressure data

Description: >
  open-meteo-api-to-s3

  Sample SAM Template for open-meteo-api-to-s3

Resources:
  FetchPressureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: fetch_pressure.handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          LATITUDE: "52.52"
          LONGITUDE: "13.41"
          LOCATION_NAME: "Berlin"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::${BucketName}/*
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)

Outputs:
  FetchPressureFunction:
    Description: "FetchPressure Lambda Function ARN"
    Value: !GetAtt FetchPressureFunction.Arn

  FetchPressureFunctionIamRole:
    Description: "Implicit IAM Role created for FetchPressure function"
    Value: !GetAtt FetchPressureFunctionRole.Arn
